name: auto-ci

on: 
  push: 
    branches: [ api ]
    
env:
  NAME: youtube_api
  TAG: prod
  IMAGE: $NAME:$TAG
  KUBECONFIG: ${{ secrets.KUBECONFIG }}
  REPO: ${{ secrets.REPO }}
  CHAT_DIR: ${{ secrets.CHART_DIR }}
  VALUES_DIR: ${{ secrets.VALUES_DIR }}

jobs:
  build-image:
    runs-on: self-hosted
    steps:
      - name: clone
        run: |
          sudo rm -rf ~/workspace/
          git clone git@github.com:nhd1207/youtube_api.git ~/workspace
          cd ~/workspace
          git checkout api
      - name: build and push image
          docker build . -t $REPO/IMAGE
          docker push $REPO/IMAGE
  deploy:
    runs-on: slef-hosted
    steps:
    - name: Update cluster
      run: |
        base64 -d $KUBECONFIG > ~/.kube/config
        helm upgrade --install --recreate-pods $CHART_DIR -f $VALUES_DIR/$NAME.yaml --set 
        
      
    
