name: auto-ci

on: 
  push: 
    branches: [ api ]
    
env:
  NAME: youtube_api
  TAG: prod
  KUBECONFIG: ${{ secrets.KUBECONFIG }}
  REPO: ${{ secrets.REPO }}
  CHAT_DIR: ${{ secrets.CHART_DIR }}
  VALUES_DIR: ${{ secrets.VALUES_DIR }}

jobs:
  build-image:
    runs-on: self-hosted
    steps:
      - name: clone
        run: |
          sudo rm -rf ~/workspace/
          git clone git@github.com:nhd1207/youtube_api.git ~/workspace
          cd ~/workspace
          git checkout api
          docker build . -t $REPO/$NAME:$TAG
          docker push $REPO/$NAME:$TAG

  deploy:
    runs-on: self-hosted
    steps:
      - name: Update cluster
        run: |
          base64 -d $KUBECONFIG > ~/.kube/config
          helm upgrade --install --recreate-pods $CHART_DIR -f $VALUES_DIR/$NAME.yaml 
        
      
    
