name: auto-ci

on: [push]

jobs:
  build-image:
    runs-on: self-hosted
    steps:
      - name: get repo
        run: |
          git clone git@github.com:nhd1207/youtube_api.git /workspace
          cd workspace
          git checkout api
          ls
