name: auto-ci

on: 
  push: 
    branches: [ api ]

jobs:
  build-image:
    runs-on: self-hosted
    steps:
      - name: get repo
        run: |
          sudo rm -rf ~/workspace/
          git clone git@github.com:nhd1207/youtube_api.git ~/workspace
          cd workspace
          git checkout api
          ls
